name: Build and publish container image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [published]

env:
  image_name: "dcagatay/mkcert"
  build_platforms: "linux/amd64,linux/arm64,linux/arm/v7"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: docker_build
        if: github.event_name == 'release'
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: ${{ env.build_platforms }}
          tags: |
            ${{ env.image_name }}:latest,${{ env.image_name }}:${{ github.ref_name }}
          build-args: |
            MKCERT_VERSION=${{ github.ref_name }}

      - name: Build and push branches
        id: docker_master_build
        if: github.event_name != 'release'
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
          platforms: ${{ env.build_platforms }}
          tags: |
            ${{ env.image_name }}:master

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v4
        if: ${{ github.ref == 'refs/heads/master' || github.event_name == 'release' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.image_name }}
